# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Build with dockerfile
      run: |
        docker build -t chufansuki_pacman:$GITHUB_SHA -f ./Dockerfile . --build-arg PYTHON_VERSION=${{ matrix.python-version }}
    - name: Run tests
      run: docker run $GITHUB_REPOSITORY:$GITHUB_SHA pytest -v


        

